---

- name: Install Crosshair
  hosts: localhost
  tasks:

  # Ensure that Debian packages are up-to-date.
  - name: Update Debian packages list
    apt:
      upgrade: safe
      update_cache: yes
    become: yes

  # Install Debian packages which provide core functionality.
  - name: Install core Debian packages
    apt:
      name: "{{ item }}"
    with_items:
      - c2hs    # Required for Cabal to install xmobar.
      - cabal-install    # Required to install Haskell packages.
      - fwupd    # Firmware updater.
      - libasound2-dev    # Requied for Cabal to install xmobar.
      - libiw-dev    # Required for Cabal to install xmobar.
      - libx11-dev    # Required for Cabal to install xmonad.
      - libxft-dev    # Required for Cabal to install xmonad-contrib.
      - libxinerama-dev    # Required for Cabal to install xmonad.
      - libxrandr-dev    # Required for Cabal to install xmonad.
      - libxss-dev    # Required for Cabal to install xmonad.
      - network-manager    # Network manager.
      - network-manager-gnome    # NetworkManager GUI.
      - network-manager-openvpn-gnome    # NetworkManager OpenVPN plugin.
      - rsync    # Required for Crosshair installation with Ansible.
      - ufw    # Firewall.
      - xorg    # X environment.
    become: yes

  # Install Haskell packages for Xmonad using Cabal. Xmonad 0.14 and
  # xmonad-contrib 0.14 are the latest versions of those packages. Xmobar 0.26
  # is not the latest version of that package, but it is the latest version
  # which can be installed with GHC 8.0.1, the version of GHC provided by
  # Debian Stretch.
  - name: Install Haskell packages
    shell: >
        cabal update &&
        cabal install xmonad-0.14 &&
        cabal install xmonad-contrib-0.14 &&
        cabal install xmobar-0.26 -f with_iwlib -f with_xft

  # Enable the firewall.
  - name: Enable UFW
    shell: ufw enable
    become: yes

  # Create /usr/share sub-directories.
  - name: Create /usr/share sub-directories
    file:
      dest: /usr/share/{{ item }}
      state: directory
    with_items:
      - icons/default
    become: yes

  # Copy dotfiles to home directory.
  - name: Copy dotfiles
    synchronize:
      src: ../files/dotfiles/
      dest: "~"

  # Copy user-dirs.default file to /etc/xdg/ directory.
  - name: Copy user-dirs.defaults
    copy:
      src: ../files/systemfiles/user-dirs.defaults
      dest: /etc/xdg/user-dirs.defaults
    become: yes

  # Create or recreate XDG user directories.
  - name: Create/recreate user directories
    shell: xdg-user-dirs-update --force

  # Copy cursor files to /usr/share/icons directory.
  - name: Copy cursor files
    synchronize:
      src: ../files/icons/Crosshair/
      dest: /usr/share/icons/Crosshair
    become: yes

  # Create the Crosshair cursor alternative in update-alternatives. Set its
  # priority to 100 to override Adwaita's priority of 90.
  - name: Create Crosshair cursor alternative
    shell: >
      update-alternatives
      --install
      /usr/share/icons/default/cursor.theme
      x-cursor-theme
      /usr/share/icons/Crosshair/cursor.theme
      100
    become: yes
